/*
 * USART_Config.h
 *
 * Created: 8/31/2023 9:43:23 AM
 *  Author: Ahmed ElSayed
 */ 


#ifndef USART_CONFIG_H_
#define USART_CONFIG_H_

#define USART_MODE				USART_ASYNC

#define USART_PARITY_MODE		USART_NO_PARITY

#define USART_STOP_BIT			USART_1_STOP_BIT

#define USART_CHR_SIZE			USART_8_BIT_CHR

#define USART_CLK_PARITY		USART_TX_RISING_EDGE

#define USART_RX_MODE			USART_RX_EN

#define USART_RX_INT_MODE		USART_RX_INT_DS

#define USART_TX_MODE			USART_TX_EN

#define USART_TX_INT_MODE		USART_TX_INT_DS

#define USART_DRE_INT_MODE		USART_DRE_INT_DS	

#define USART_DDR_MODE			USART_DDR_DS

#define USART_MULTI_ECU_MODE	USART_MULTI_ECU_DS

#endif /* USART_CONFIG_H_ */